-- ====================================================================
-- EchoVision (PhonoSpatial HUD) - Migración 005: Esquema Relacional con Enums
-- Enums, profiles extendido, spatial_zones, devices, custom_sound_signatures,
-- acoustic_incidents, incident_telemetry_frames, emergency_contacts,
-- notification_dispatch_logs, dosimetry_daily_aggregates y tr_critical_escalation
-- ====================================================================

-- 1. TIPOS ENUMERADOS
DO $$ BEGIN
  CREATE TYPE risk_level_enum AS ENUM ('NORMAL', 'ADVISORY', 'CRITICAL');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE device_type_enum AS ENUM ('LAPTOP_HUD', 'MOBILE_COMPANION', 'IOT_EDGE_MICROPHONE');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE notification_channel_enum AS ENUM ('GMAIL', 'WEBHOOK_IOT', 'SMS');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE dispatch_status_enum AS ENUM ('PENDING', 'SENT', 'FAILED', 'ACKNOWLEDGED');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- 2. PERFILES Y PREFERENCIAS DE ACCESIBILIDAD
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name text,
  emergency_email text,
  haptic_enabled boolean DEFAULT true,
  strobe_enabled boolean DEFAULT true,
  high_contrast_mode boolean DEFAULT false,
  global_sensitivity_threshold float DEFAULT 0.75,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS emergency_email text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS haptic_enabled boolean DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS strobe_enabled boolean DEFAULT true;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS high_contrast_mode boolean DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS global_sensitivity_threshold float DEFAULT 0.75;

-- 3. ZONAS ESPACIALES / HABITACIONES
CREATE TABLE IF NOT EXISTS public.spatial_zones (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  zone_name text NOT NULL, -- ej: 'Cocina', 'Dormitorio Principal'
  ambient_noise_floor_db float DEFAULT 40.0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- 4. DISPOSITIVOS SENSORES (MESH TOPOLOGY)
CREATE TABLE IF NOT EXISTS public.devices (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  zone_id uuid REFERENCES public.spatial_zones ON DELETE SET NULL,
  device_name text NOT NULL,
  device_type device_type_enum DEFAULT 'LAPTOP_HUD',
  battery_level int,
  is_online boolean DEFAULT true,
  last_heartbeat timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);

-- 5. CATÁLOGO DE HUELLAS ACÚSTICAS PERSONALIZADAS
CREATE TABLE IF NOT EXISTS public.custom_sound_signatures (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  label text,
  spectral_centroid_hz float,
  mfcc_signature jsonb,
  default_risk risk_level_enum DEFAULT 'ADVISORY',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.custom_sound_signatures ADD COLUMN IF NOT EXISTS label text;
ALTER TABLE public.custom_sound_signatures ADD COLUMN IF NOT EXISTS spectral_centroid_hz float;
ALTER TABLE public.custom_sound_signatures ADD COLUMN IF NOT EXISTS mfcc_signature jsonb;
ALTER TABLE public.custom_sound_signatures ADD COLUMN IF NOT EXISTS default_risk risk_level_enum DEFAULT 'ADVISORY';

-- 6. INCIDENTES ACÚSTICOS (TABLA CENTRAL DE REGISTRO)
CREATE TABLE IF NOT EXISTS public.acoustic_incidents (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  device_id uuid REFERENCES public.devices ON DELETE SET NULL,
  zone_id uuid REFERENCES public.spatial_zones ON DELETE SET NULL,
  sound_label text NOT NULL,
  confidence float NOT NULL,
  peak_decibels float NOT NULL,
  azimuth_angle float NOT NULL, -- 0 a 360 grados
  risk_level risk_level_enum NOT NULL,
  is_acknowledged boolean DEFAULT false,
  acknowledged_at timestamptz,
  created_at timestamptz DEFAULT now()
);

-- 7. SUB-MUESTREO DE TELEMETRÍA DE LA ONDA (PARA ANÁLISIS FORENSE)
CREATE TABLE IF NOT EXISTS public.incident_telemetry_frames (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id uuid REFERENCES public.acoustic_incidents ON DELETE CASCADE NOT NULL,
  fft_spectrum_bins jsonb NOT NULL, -- Snapshot de los 64/128 bins de frecuencia
  timestamp_offset_ms int NOT NULL
);

-- 8. DIRECTORIO DE CONTACTOS DE EMERGENCIA
CREATE TABLE IF NOT EXISTS public.emergency_contacts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  contact_name text,
  email text NOT NULL,
  phone text,
  priority_order int DEFAULT 1,
  notify_on_critical boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.emergency_contacts ADD COLUMN IF NOT EXISTS contact_name text;
ALTER TABLE public.emergency_contacts ADD COLUMN IF NOT EXISTS priority_order int DEFAULT 1;
ALTER TABLE public.emergency_contacts ADD COLUMN IF NOT EXISTS notify_on_critical boolean DEFAULT true;

-- 9. LOG DE DESPACHOS Y AUDITORÍA DE NOTIFICACIONES (GMAIL / IOT)
DROP TABLE IF EXISTS public.notification_dispatch_logs CASCADE;

CREATE TABLE public.notification_dispatch_logs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  incident_id uuid REFERENCES public.acoustic_incidents ON DELETE CASCADE,
  contact_id uuid REFERENCES public.emergency_contacts ON DELETE SET NULL,
  channel notification_channel_enum NOT NULL DEFAULT 'GMAIL',
  status dispatch_status_enum DEFAULT 'PENDING',
  payload_summary jsonb,
  dispatched_at timestamptz DEFAULT now(),
  acknowledged_at timestamptz
);

-- 10. AGREGADOS DIARIOS DE DOSIMETRÍA AUDITIVA
CREATE TABLE IF NOT EXISTS public.dosimetry_daily_aggregates (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  date date NOT NULL,
  cumulative_noise_dose_pct float DEFAULT 0.0, -- Límite OMS = 100%
  peak_recorded_db float DEFAULT 0.0,
  critical_events_count int DEFAULT 0,
  UNIQUE(user_id, date)
);

-- 11. AUTOMATIZACIÓN EN BASE DE DATOS: TRIGGER DE AUTO-ESCALAMIENTO
CREATE OR REPLACE FUNCTION trigger_critical_incident_escalation()
RETURNS trigger AS $$
BEGIN
  IF new.risk_level = 'CRITICAL' THEN
    -- Insertar un despacho pendiente para cada contacto de emergencia activo
    INSERT INTO public.notification_dispatch_logs (incident_id, contact_id, channel, status, payload_summary)
    SELECT 
      new.id, 
      c.id, 
      'GMAIL'::notification_channel_enum, 
      'PENDING'::dispatch_status_enum, 
      jsonb_build_object(
        'sound_label', new.sound_label,
        'decibels', new.peak_decibels,
        'zone_id', new.zone_id,
        'timestamp', new.created_at
      )
    FROM public.emergency_contacts c
    WHERE c.user_id = new.user_id AND (c.notify_on_critical = true OR c.is_active = true);
  END IF;
  RETURN new;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_critical_escalation ON public.acoustic_incidents;
CREATE TRIGGER tr_critical_escalation
AFTER INSERT ON public.acoustic_incidents
FOR EACH ROW EXECUTE FUNCTION trigger_critical_incident_escalation();

-- 12. ROW LEVEL SECURITY (RLS) PARA LAS NUEVAS TABLAS
ALTER TABLE public.spatial_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acoustic_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incident_telemetry_frames ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_dispatch_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dosimetry_daily_aggregates ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "Users manage own spatial zones"
    ON public.spatial_zones FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Users manage own devices"
    ON public.devices FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Users read own acoustic incidents"
    ON public.acoustic_incidents FOR SELECT
    USING (auth.uid() = user_id OR user_id IS NULL);
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Authenticated and ingest can insert acoustic incidents"
    ON public.acoustic_incidents FOR INSERT
    WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'service_role' OR auth.role() = 'anon');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Users read incident telemetry frames"
    ON public.incident_telemetry_frames FOR SELECT
    USING (EXISTS (
      SELECT 1 FROM public.acoustic_incidents ai 
      WHERE ai.id = incident_telemetry_frames.incident_id 
      AND (ai.user_id = auth.uid() OR ai.user_id IS NULL)
    ));
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Users read own notification logs"
    ON public.notification_dispatch_logs FOR SELECT
    USING (true);
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
  CREATE POLICY "Users manage own dosimetry aggregates"
    ON public.dosimetry_daily_aggregates FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- 13. CONFIGURACIÓN DE SUPABASE REALTIME PARA ACOUSTIC_INCIDENTS
ALTER TABLE public.acoustic_incidents REPLICA IDENTITY FULL;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables 
      WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'acoustic_incidents'
    ) THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.acoustic_incidents;
    END IF;
  END IF;
END $$;
